# Generated by Django 3.0.3 on 2024-11-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcard', '0002_auto_20241102_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_no',
            field=models.CharField(max_length=100),
        ),
    ]
